version: '3'

services:
  controller:
    build:
      context: .
      dockerfile: Dockerfile.grafanaserver
    hostname: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
  database:
    build:
      context: .
      dockerfile: Dockerfile.database
    hostname: database
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always